Should probably note that this is a test file for various project parts that don't have testing yet.

In [5]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [35]:
from tools import *

filename = 'vanilla-rawdata.json'
FactorioInstance(filename)

INFO:root:Starting construct generation of machines in category: boiler
INFO:root:Starting construct generation of machines in category: burner-generator
INFO:root:Starting construct generation of machines in category: offshore-pump
INFO:root:Starting construct generation of machines in category: reactor
INFO:root:Starting construct generation of machines in category: generator
INFO:root:Starting construct generation of machines in category: furnace
INFO:root:Starting construct generation of machines in category: mining-drill
INFO:root:Starting construct generation of machines in category: solar-panel
INFO:root:Starting construct generation of machines in category: rocket-silo
INFO:root:Starting construct generation of machines in category: assembling-machine


In [9]:
def A(**kwargs):
    B(**kwargs)

def B(stat = 5, **kwargs):
    print(stat)
    C(**kwargs)

def C(bat = 5):
    print(bat)

A(stat=4, bat=8)

4
8


In [7]:
import numpy as np
from fractions import Fraction

Fraction(10000000000000000000) < np.inf
Fraction(np.inf)

OverflowError: cannot convert Infinity to integer ratio

In [4]:
import linearconstructs

combinations = set()
for comb in linearconstructs.integer_module_options([("Both A", True, True), ("Both B", True, True), ("Internal", True, False), ("External", False, True)], 5, 8):
    print(comb)
    combinations.add(frozenset([(k, v) for k, v in comb.items()]))
print(len(combinations))

{}
{'Both A-e': 1}
{'Both B-e': 1}
{'External-e': 1}
{'Both A-e': 2}
{'Both A-e': 1, 'Both B-e': 1}
{'Both A-e': 1, 'External-e': 1}
{'Both B-e': 2}
{'Both B-e': 1, 'External-e': 1}
{'External-e': 2}
{'Both A-e': 3}
{'Both A-e': 2, 'Both B-e': 1}
{'Both A-e': 2, 'External-e': 1}
{'Both A-e': 1, 'Both B-e': 2}
{'Both A-e': 1, 'Both B-e': 1, 'External-e': 1}
{'Both A-e': 1, 'External-e': 2}
{'Both B-e': 3}
{'Both B-e': 2, 'External-e': 1}
{'Both B-e': 1, 'External-e': 2}
{'External-e': 3}
{'Both A-e': 4}
{'Both A-e': 3, 'Both B-e': 1}
{'Both A-e': 3, 'External-e': 1}
{'Both A-e': 2, 'Both B-e': 2}
{'Both A-e': 2, 'Both B-e': 1, 'External-e': 1}
{'Both A-e': 2, 'External-e': 2}
{'Both A-e': 1, 'Both B-e': 3}
{'Both A-e': 1, 'Both B-e': 2, 'External-e': 1}
{'Both A-e': 1, 'Both B-e': 1, 'External-e': 2}
{'Both A-e': 1, 'External-e': 3}
{'Both B-e': 4}
{'Both B-e': 3, 'External-e': 1}
{'Both B-e': 2, 'External-e': 2}
{'Both B-e': 1, 'External-e': 3}
{'External-e': 4}
{'Both A-e': 5}
{'Both 

In [2]:
import json
data = None

with open('vanilla-rawdata.txt') as f:
    data = json.load(f)

data['recipe']['basic-oil-processing']

{'type': 'recipe',
 'name': 'basic-oil-processing',
 'category': 'oil-processing',
 'enabled': False,
 'energy_required': 5,
 'ingredients': [{'type': 'fluid',
   'name': 'crude-oil',
   'amount': 100,
   'fluidbox_index': 2}],
 'results': [{'type': 'fluid',
   'name': 'petroleum-gas',
   'amount': 45,
   'fluidbox_index': 3}],
 'icon': '__base__/graphics/icons/fluid/basic-oil-processing.png',
 'icon_size': 64,
 'icon_mipmaps': 4,
 'subgroup': 'fluid-recipes',
 'order': 'a[oil-processing]-a[basic-oil-processing]',
 'main_product': ''}

In [3]:
%%prun
import logging
logging.basicConfig(level=logging.INFO)

from utils import *
from generators import *
from constructs import *
from solver import *

complete_premanagement(data)
all_constructs = generate_all_constructs(data)

INFO:root:Starting processing of category: boiler
INFO:root:Starting processing of category: burner-generator
INFO:root:Starting processing of category: offshore-pump
INFO:root:Starting processing of category: reactor
INFO:root:Starting processing of category: generator
INFO:root:Starting processing of category: furnace
INFO:root:Starting processing of category: mining-drill
INFO:root:Starting processing of category: solar-panel
INFO:root:Starting processing of category: rocket-silo
INFO:root:Starting processing of category: assembling-machine


         562557 function calls (538128 primitive calls) in 1.586 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1920    0.174    0.000    0.174    0.000 {method 'acquire' of '_thread.lock' objects}
       70    0.172    0.002    0.173    0.002 {built-in method _imp.create_dynamic}
      326    0.157    0.000    0.157    0.000 {built-in method io.open_code}
      326    0.096    0.000    0.096    0.000 {method 'read' of '_io.BufferedReader' objects}
     1021    0.093    0.000    0.093    0.000 utils.py:84(<listcomp>)
     1356    0.086    0.000    0.086    0.000 {built-in method nt.stat}
        1    0.066    0.066    0.269    0.269 utils.py:224(link_techs)
    12632    0.063    0.000    0.074    0.000 utils.py:140(listunion)
      723    0.061    0.000    0.061    0.000 socket.py:621(send)
      324    0.039    0.000    0.039    0.000 {built-in method marshal.loads}
12824/192    0.022    0.000    0.099    0.001 utils

In [4]:
for construct in all_constructs:
    print(construct)
    print("\n")

water to steam@165 in boiler via wood
	With a vector of: {'wood': -0.9, 'water': -60.0, 'steam@165': 60.0}
	An added drain of: {}
	An effect matrix of: {'speed': [], 'productivity': [], 'consumption': [], 'pollution': []}
	Allowed Modules: []
	Base Inputs of: {'wood': -0.9}
	A Cost of: {'boiler': 1}
	Requiring: 


water to steam@165 in boiler via coal
	With a vector of: {'coal': -0.45, 'water': -60.0, 'steam@165': 60.0}
	An added drain of: {}
	An effect matrix of: {'speed': [], 'productivity': [], 'consumption': [], 'pollution': []}
	Allowed Modules: []
	Base Inputs of: {'coal': -0.45}
	A Cost of: {'boiler': 1}
	Requiring: 


water to steam@165 in boiler via solid-fuel
	With a vector of: {'solid-fuel': -0.15, 'water': -60.0, 'steam@165': 60.0}
	An added drain of: {}
	An effect matrix of: {'speed': [], 'productivity': [], 'consumption': [], 'pollution': []}
	Allowed Modules: []
	Base Inputs of: {'solid-fuel': -0.15}
	A Cost of: {'boiler': 1}
	Requiring: 


water to steam@165 in boiler v

In [5]:
all_constructs[1]

water to steam@165 in boiler via coal
	With a vector of: {'coal': -0.45, 'water': -60.0, 'steam@165': 60.0}
	An added drain of: {}
	An effect matrix of: {'speed': [], 'productivity': [], 'consumption': [], 'pollution': []}
	Allowed Modules: []
	Base Inputs of: {'coal': -0.45}
	A Cost of: {'boiler': 1}
	Requiring: 

In [6]:
%prun all_families, reference_list = generate_all_construct_families(all_constructs)

         4166658 function calls (4123333 primitive calls) in 3.341 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    45582    0.910    0.000    1.892    0.000 sparsetensors.py:22(_itemization_)
   661888    0.292    0.000    0.384    0.000 index_tricks.py:594(__next__)
     1302    0.291    0.000    2.669    0.002 constructs.py:175(true_construct)
      214    0.257    0.001    0.371    0.002 constructs.py:362(all_descendants)
    43911    0.113    0.000    0.131    0.000 sparsetensors.py:114(set_item_function)
   667592    0.109    0.000    0.109    0.000 {method 'add' of 'set' objects}
    20832    0.107    0.000    0.107    0.000 sparsetensors.py:11(__init__)
    28044    0.094    0.000    0.094    0.000 {method 'index' of 'list' objects}
   624615    0.093    0.000    0.118    0.000 {built-in method builtins.isinstance}
   661888    0.092    0.000    0.092    0.000 {built-in method builtins.next}
     2910    0.091   

In [7]:
reference_list

['iron-ore',
 'speed-module-3',
 'piercing-rounds-magazine',
 'modular-armor',
 'long-handed-inserter',
 'military-science-pack',
 'flamethrower',
 'centrifuge',
 'hazard-concrete',
 'fluid-wagon',
 'uranium-rounds-magazine',
 'green-wire',
 'electric-engine-unit',
 'pistol',
 'logistic-chest-passive-provider',
 'filter-inserter',
 'roboport',
 'heat',
 'lubricant',
 'water',
 'personal-laser-defense-equipment',
 'electric-furnace',
 'petroleum-gas',
 'radar',
 'destroyer-capsule',
 'copper-cable',
 'fast-splitter',
 'loader',
 'light-oil-barrel',
 'solar-panel-equipment',
 'personal-roboport-mk2-equipment',
 'rail-chain-signal',
 'grenade',
 'iron-stick',
 'crude-oil-barrel',
 'shotgun',
 'burner-inserter',
 'cargo-wagon',
 'power-armor-mk2',
 'decider-combinator',
 'logistic-robot',
 'battery-mk2-equipment',
 'spidertron-remote',
 'construction-robot',
 'night-vision-equipment',
 'stone-brick',
 'stone-wall',
 'substation',
 'fusion-reactor-equipment',
 'rail',
 'flamethrower-turret'

In [17]:
starting_pricing_model = {}
for k in reference_list:
    starting_pricing_model.update({k: 1})
optimize_for_outputs_via_reference_model(all_families, reference_list, {'automation-science-pack': 1}, data['recipe']['chemical-science-pack']['limit'], starting_pricing_model, 'SLSQP')

INFO:root:solve_optimization_problem doesn't actually use output_type for... reasons.


water to steam@165 in boiler via wood
	With a vector of: {'wood': -0.9, 'water': -60.0, 'steam@165': 60.0}
	An added drain of: {}
	An effect matrix of: {'speed': [], 'productivity': [], 'consumption': [], 'pollution': []}
	Allowed Modules: []
	Base Inputs of: {'wood': -0.9}
	A Cost of: {'boiler': 1}
	Requiring: 
water to steam@165 in boiler via coal
	With a vector of: {'coal': -0.45, 'water': -60.0, 'steam@165': 60.0}
	An added drain of: {}
	An effect matrix of: {'speed': [], 'productivity': [], 'consumption': [], 'pollution': []}
	Allowed Modules: []
	Base Inputs of: {'coal': -0.45}
	A Cost of: {'boiler': 1}
	Requiring: 
water to steam@165 in boiler via solid-fuel
	With a vector of: {'solid-fuel': -0.15, 'water': -60.0, 'steam@165': 60.0}
	An added drain of: {}
	An effect matrix of: {'speed': [], 'productivity': [], 'consumption': [], 'pollution': []}
	Allowed Modules: []
	Base Inputs of: {'solid-fuel': -0.15}
	A Cost of: {'boiler': 1}
	Requiring: 
water to steam@165 in boiler via roc

INFO:root: message: Optimization terminated successfully
 success: True
  status: 0
     fun: 27.13888927670103
       x: [ 7.850e-01  1.000e+00 ...  0.000e+00  0.000e+00]
     nit: 12
     jac: [ 0.000e+00  0.000e+00 ...  1.000e+00  1.000e+00]
    nfev: 3619
    njev: 11
INFO:root:Optimal phi found to be: []
INFO:root:Optimal theta found to be: [0.78501888 1.         0.79947044 0.78503788 0.78503893 1.
 1.         0.99999384 0.79995429 1.         0.60065201 0.79995493
 0.79995497 0.89434289 1.         0.99378654 0.89434382 0.89434387
 0.98539691 0.99154398 0.9861195  0.98539787 0.98539792 0.98539691
 0.99938239 0.9861195  0.98539787 0.98539792 1.         1.
 1.         0.98791182 0.99911709 0.35324535 0.6772196  0.86364047
 0.3532457  0.35324572 0.47158688 0.93896333 0.9411317  0.47158789
 0.47158795 0.56051239 0.92923792 0.88878915 0.56051357 0.56051364
 0.94173185 0.99525654 0.94293616 0.94173344 0.94173353 0.94173185
 0.99921115 0.94293616 0.94173344 0.94173353 0.9939046  0.9954457


Determined optimal setup to be: 
0.9553306185753146 x " water to steam@165 in boiler via coal " with usage:  [1.]  and setup:  []
0.047766530928140684 x " offshore-pump " with usage:  [1.]  and setup:  []
1.9106612371524199 x " electric from steam-engine via steam@165 " with usage:  [1.]  and setup:  []
3.1999999999989486 x " copper-plate in stone-furnace with coal " with usage:  [1.]  and setup:  []
6.399999999999018 x " iron-plate in stone-furnace with coal " with usage:  [1.]  and setup:  []
3.9999999999989178 x " electric-mining-drill mining: iron-ore " with usage:  [1.]  and setup:  []
1.9999999999989448 x " electric-mining-drill mining: copper-ore " with usage:  [1.]  and setup:  []
1.2917975567179623 x " electric-mining-drill mining: coal " with usage:  [1.]  and setup:  []
0.666666666665632 x " iron-gear-wheel in assembling-machine-2 with electric " with usage:  [1.]  and setup:  []
6.666666666665729 x " automation-science-pack in assembling-machine-2 with electric " with usag

INFO:root:[0 2 0 0 0 0 1 0 0 2 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
INFO:root:[0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
INFO:root:(164, 214)
INFO:root: message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 0.0
       x: [ 0.000e+00  0.000e+00 ...  0.000e+00  0.000e+00]
     nit: 9



Determined pricing model to be: 
copper-plate  = $ 5.787392670157113
copper-ore  = $ 2.413612565444967
coal  = $ 2.413612565444986
water  = $ 0.0008333333333333251
iron-plate  = $ 5.7873926701568426
iron-ore  = $ 2.4136125654449003
electric  = $ 2.2978475858054377e-06
iron-gear-wheel  = $ 12.463577273608198
automation-science-pack  = $ 27.138889276710906
steam@165  = $ 0.03560209424084004
 

         19626861 function calls (19446714 primitive calls) in 19.944 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    2.981    2.981    4.579    4.579 _slsqp_py.py:214(_minimize_slsqp)
   553582    2.063    0.000    2.063    0.000 {method 'reduce' of 'numpy.ufunc' objects}
    72381    1.957    0.000   12.751    0.000 sparsetensors.py:415(einstein_summation_sparse)
   226667    1.815    0.000    3.682    0.000 sparsetensors.py:22(_itemization_)
   553362    1.090    0.000    3.932    0.000 fromnumeric.py:69(_wrapreduction)
746509/568286    0.586    0.000    6.528    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
   223149    0.510    0.000    0.666    0.000 sparsetensors.py:399(sparse_match)
  3119924    0.472    0.000    0.635    0.000 {built-in method builtins.isinstance}
   446298    0.459    0.000    3.899    0.000 fromnumeric.py:2970(prod)
    35260    0.445    0.000   14.786

In [20]:
data['recipe']['chemical-science-pack']['limit']

chemical-science-pack and advanced-electronics and plastics and oil-processing and fluid-handling and automation-2 and electronics and automation and steel-processing and logistic-science-pack and engine and sulfur-processing

In [89]:
from utils import *
from generators import *
from constructs import *
from solver import *

method_to_use = "COBYLA"

testing_constructs = [UncompiledConstruct("Constuct A", {'p': -1}, {'a': 1, 'p': -10}, 
                                          {'speed': ['a'], 'productivity': ['a'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={'p': -11}, cost={'c': 1}, limit=TechnologicalLimitation([[]])),
                      UncompiledConstruct("Constuct B", {'p': -3}, {'b': 1, 'p': -50}, 
                                          {'speed': ['b'], 'productivity': ['b'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={'p': -7}, cost={'c': 1}, limit=TechnologicalLimitation([[]])),
                      UncompiledConstruct("Constuct C", {'p': -5}, {'c': 1, 'p': -100, 'a': -3, 'b': -5}, 
                                          {'speed': ['a', 'b', 'c'], 'productivity': ['c'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={'p': -7}, cost={'c': 1}, limit=TechnologicalLimitation([[]])),
                      UncompiledConstruct("Constuct P", {}, {'p': 100}, 
                                          {'speed': ['b'], 'productivity': ['b'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={}, cost={'c': 3}, limit=TechnologicalLimitation([[]])),
                      UncompiledConstruct("Constuct bA", {'p': -2}, {'a': 1, 'p': -15}, 
                                          {'speed': ['a'], 'productivity': ['a'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={'p': -11}, cost={'c': 1}, limit=TechnologicalLimitation([[]])),
                      UncompiledConstruct("Constuct bB", {'p': -3}, {'b': 1, 'p': -50}, 
                                          {'speed': ['b'], 'productivity': ['b'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={'p': -7}, cost={'c': 2}, limit=TechnologicalLimitation([[]])),
                      UncompiledConstruct("Constuct bC", {'p': -5}, {'c': 1, 'p': -100, 'a': -4, 'b': -6}, 
                                          {'speed': ['a', 'b', 'c'], 'productivity': ['c'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={'p': -7}, cost={'c': 1, 'a': 1}, limit=TechnologicalLimitation([[]])),
                      UncompiledConstruct("Constuct bP", {}, {'p': 88}, 
                                          {'speed': ['b'], 'productivity': ['b'], 'consumption': ['p']}, [(m,1) for m in data['module'].values()],
                                          base_inputs={}, cost={'c': 3}, limit=TechnologicalLimitation([[]])),]
testing_family, testing_references = generate_all_construct_families(testing_constructs)
starting_pricing_model = {'a': 1, 'b': 3, 'c': 30, 'p': .08}
logging.info(testing_references)
testing_R_i, testing_phi_i, testing_thetas, testing_s_i, testing_p_i = optimize_for_outputs_via_reference_model(testing_family, testing_references, 
                                                                                                                {'c': 1}, TechnologicalLimitation([[]]), starting_pricing_model, method_to_use)

prebuilt_testing_R_i = [(s*c.freeze(phi)) for c, s, phi in zip([f.base_case for f in testing_family], testing_s_i.tolist(), testing_phi_i)]
testing_u_j = np.zeros(len(testing_references))
for k, v in {'c': 1}.items():
    testing_u_j[testing_references.index(k)] = v
testing_prebuilt_p_i = calculate_pricing_model_via_prebuilt(prebuilt_testing_R_i, testing_u_j, 'trust-constr', universal_reference_list=testing_references)

iterative_pricing_model(testing_family, testing_references, {'c': 1}, TechnologicalLimitation([[]]), method_to_use, 10, starting_pricing_model)

INFO:root:['speed-module-3', 'productivity-module', 'a', 'effectivity-module', 'c', 'effectivity-module-3', 'productivity-module-3', 'speed-module', 'productivity-module-2', 'speed-module-2', 'effectivity-module-2', 'p', 'b']
INFO:root:solve_optimization_problem doesn't actually use output_type for... reasons.
INFO:root:====================================
INFO:root:Determined optimal setup to be: 
INFO:root:2.9999999999999982x "Constuct A" with usage: [1.] and setup: []
INFO:root:4.9999999999999964x "Constuct B" with usage: [1.] and setup: []
INFO:root:1.0000000000000002x "Constuct C" with usage: [1.] and setup: []
INFO:root:4.0299999999999985x "Constuct P" with usage: [1.] and setup: []
INFO:root:====================================
INFO:root:====================================
INFO:root:Determined pricing model to be: [  0.    0.   39.9   0.  632.7   0.    0.    0.    0.    0.    0.    0.9
  77.7]
INFO:root:a = $39.899999999999984
INFO:root:c = $632.6999999999999
INFO:root:p = $0.8

array([    0.        ,     0.        ,   630.63063063,     0.        ,
       10000.        ,     0.        ,     0.        ,     0.        ,
           0.        ,     0.        ,     0.        ,    14.22475107,
        1228.07017544])

In [32]:
tech_limit = tech_objection_via_spec({"fully_automated": ['automation-science-pack']}, data)
goals = {'automation-science-pack': 1}
pricing_model = {}
for k in reference_list:
    pricing_model.update({k: 1})
%prun active_R_i, active_phi_i, active_thetas, active_s_i, active_p_i = optimize_for_outputs_via_reference_model(all_families, reference_list, goals, tech_limit, pricing_model, 'SLSQP')

INFO:root:Making a tech specification via dict.
INFO:root:Tech specification: physical-projectile-damage-1 and weapon-shooting-speed-1 and automation and electronics and logistic-science-pack and steel-processing and steel-axe and military and fast-inserter and logistics and optics and heavy-armor and gun-turret and stone-wall
INFO:root:solve_optimization_problem doesn't actually use output_type for... reasons.
INFO:root:====================================
INFO:root:Determined optimal setup to be: 
INFO:root:0.8006864455823104x "water to steam@165 in boiler via coal" with usage: [1.] and setup: []
INFO:root:0.0400343222842345x "offshore-pump" with usage: [1.] and setup: []
INFO:root:1.6013728912082974x "electric from steam-engine via steam@165" with usage: [1.] and setup: []
INFO:root:3.2000000000160016x "copper-plate in stone-furnace with coal" with usage: [1.] and setup: []
INFO:root:6.400000000015017x "iron-plate in stone-furnace with coal" with usage: [1.] and setup: []
INFO:root:

102
214
(316, 214)
(316,)
 

         144534342 function calls (144529187 primitive calls) in 137.579 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  4737974   22.266    0.000   22.266    0.000 {method 'reduce' of 'numpy.ufunc' objects}
  2399576   20.459    0.000   43.660    0.000 sparsetensors.py:22(_itemization_)
    46805   17.305    0.000  135.595    0.003 sparsetensors.py:415(einstein_summation_sparse)
  4736112   10.673    0.000   41.460    0.000 fromnumeric.py:69(_wrapreduction)
  2366930    6.783    0.000    9.099    0.000 sparsetensors.py:399(sparse_match)
  2366930    5.644    0.000    6.641    0.000 sparsetensors.py:155(add_item_function)
  4733860    5.628    0.000   47.070    0.000 fromnumeric.py:2970(prod)
  4734929    5.148    0.000    5.148    0.000 {built-in method builtins.getattr}
 26962110    4.842    0.000    6.707    0.000 {built-in method builtins.isinstance}
  2366930    3.898    0.000    4.984    0.000 sparsetensors.py:436(<

In [23]:
print(len(active_p_i))
active_u_j = np.zeros(len(reference_list))
for k, v in goals.items():
    active_u_j[reference_list.index(k)] = v
calculate_pricing_model_via_prebuilt(active_R_i, active_u_j, 'SLSQP', universal_reference_list=reference_list)

INFO:root:====================================
INFO:root:Determined thetas to be: 
INFO:root:water to steam@165 in boiler via wood: [1.]
INFO:root:water to steam@165 in boiler via coal: [1.]
INFO:root:water to steam@165 in boiler via solid-fuel: [1.]
INFO:root:water to steam@165 in boiler via rocket-fuel: [1.]
INFO:root:water to steam@165 in boiler via nuclear-fuel: [1.]
INFO:root:offshore-pump: [1.]
INFO:root:electric from steam-engine via steam@165: [1.]
INFO:root:electric from steam-engine via steam@500: [1.]
INFO:root:copper-plate in stone-furnace with wood: [1.]
INFO:root:copper-plate in stone-furnace with coal: [1.]
INFO:root:copper-plate in stone-furnace with solid-fuel: [1.]
INFO:root:copper-plate in stone-furnace with rocket-fuel: [1.]
INFO:root:copper-plate in stone-furnace with nuclear-fuel: [1.]
INFO:root:iron-plate in stone-furnace with wood: [1.]
INFO:root:iron-plate in stone-furnace with coal: [1.]
INFO:root:iron-plate in stone-furnace with solid-fuel: [1.]
INFO:root:iro

214


INFO:root:lab in assembling-machine-1 with electric: [1.]
INFO:root:stone-wall in assembling-machine-1 with electric: [1.]
INFO:root:splitter in assembling-machine-1 with electric: [1.]
INFO:root:underground-belt in assembling-machine-1 with electric: [1.]
INFO:root:loader in assembling-machine-1 with electric: [1.]
INFO:root:iron-chest in assembling-machine-1 with electric: [1.]
INFO:root:shotgun in assembling-machine-1 with electric: [1.]
INFO:root:shotgun-shell in assembling-machine-1 with electric: [1.]
INFO:root:heavy-armor in assembling-machine-1 with electric: [1.]
INFO:root:steel-chest in assembling-machine-1 with electric: [1.]
INFO:root:fast-loader in assembling-machine-1 with electric: [1.]
INFO:root:express-loader in assembling-machine-1 with electric: [1.]
INFO:root:electric-energy-interface in assembling-machine-1 with electric: [1.]
INFO:root:====================================
INFO:root:====================================
INFO:root:Determined pricing model to be: 
INF

array([1.43357236e+03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.17102883e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [10]:
from utils import *
from generators import *
from constructs import *

testing_constuct_A = UncompiledConstruct("test1", {'balls': -69}, {'nuts': 420, 'capybara': -3, 'memepower': -111}, 
                                         {'speed': ['nuts', 'capybara'], 'productivity': ['nuts'], 'consumption': ['memepower']},
                                         [(m,1) for m in data['module'].values()],
                                         base_inputs={'capybara': -9}, cost={'meme': 2}, limit=TechnologicalLimitation([[]]))
testing_constuct_B = UncompiledConstruct("test2", {'ligma': -7}, {'balls': 18, 'crack': -48, 'memepower': -232}, 
                                         {'speed': ['balls', 'crack'], 'productivity': ['balls'], 'consumption': ['memepower']},
                                         [(m,1) for m in data['module'].values()],
                                         base_inputs={'crack': -2}, cost={'doge': 3}, limit=TechnologicalLimitation([[]]))
print(testing_constuct_A)
print(testing_constuct_B)
testing_family_pre, testing_references = generate_all_construct_families([testing_constuct_A, testing_constuct_B])
compiled_construct = Build_New_Construct([c.omni_case for c in testing_family_pre], np.array([3,13]), 
                                         [(testing_references.index('balls'), 1), (testing_references.index('balls'), -1)])
print("============================")
print(testing_references)
print("============================")
print(compiled_construct.ident)
#print([tens for tens in testing_family[0].omni_case.effect_tensors])
phi = np.array([.25,0,0,0,.25,0,0,0,.5, 0,0,.1,0,0,.4,0,.5,0])
theta = np.array([.75,.8589])
print("Theta bounds:")
for half_shell_index in range(compiled_construct.theta_tensors[0].shape[0]):
    value = compiled_construct.theta_tensors[0].to_dense()[half_shell_index]
    value += einstein_summation('ij,j', compiled_construct.theta_tensors[1].to_dense(),
                                theta)[half_shell_index]
    value += einstein_summation('ijk,j,k', compiled_construct.theta_tensors[2].to_dense(),
                                theta, phi)[half_shell_index]
    value += einstein_summation('ijkl,j,k,l', compiled_construct.theta_tensors[3].to_dense(),
                                theta, phi, phi)[half_shell_index]
    value += einstein_summation('ijklm,j,k,l,m', compiled_construct.theta_tensors[4].to_dense(),
                                theta, phi, phi, phi)[half_shell_index]
    print(str(value)+' <= 0 | '+str(eval(str(value)+' <= 0')))
print('Phi bounds:')
for half_shell_index in range(compiled_construct.phi_tensors[0].shape[0]):
    value = compiled_construct.phi_tensors[0].to_dense()[half_shell_index]
    value += einstein_summation('ij,j', compiled_construct.phi_tensors[1].to_dense(),
                                phi)[half_shell_index]
    print(str(value)+' <= 0 | '+str(eval(str(value)+' <= 0')))
print("Cost:")
print(compiled_construct.cost_tensors[0].to_dense() + einstein_summation('ij,j', compiled_construct.cost_tensors[1], phi))
print("Effect evaluation:")
for i in range(len(testing_references)):
    value = compiled_construct.effect_tensors[0].to_dense()[i]
    value += einstein_summation('ij,j', compiled_construct.effect_tensors[1], theta)[i]
    value += einstein_summation('ijk,j,k', compiled_construct.effect_tensors[2], 
                                theta, phi)[i]
    value += einstein_summation('ijkl,j,k,l', compiled_construct.effect_tensors[3], 
                                theta, phi, phi)[i]
    value += einstein_summation('ijklm,j,k,l,m', compiled_construct.effect_tensors[4], 
                                theta, phi, phi, phi)[i]
    if value!=0:
        print(testing_references[i]+': '+str(value))
compiled_construct.freeze(phi)

DEBUG:root:Generating construct families from an uncompiled construct list of length 2.
DEBUG:root:Creating a reference list for a total of 2 constructs.
DEBUG:root:A total of 17 items/fluids were found for the reference list.
DEBUG:root:{'effectivity-module-2', 'ligma', 'speed-module-2', 'capybara', 'speed-module', 'productivity-module', 'doge', 'meme', 'effectivity-module-3', 'nuts', 'productivity-module-2', 'speed-module-3', 'balls', 'productivity-module-3', 'memepower', 'crack', 'effectivity-module'}
DEBUG:root:Determining the catalysts present in a total of 2 constructs.
DEBUG:root:Creating a reference list for a total of 2 constructs.
DEBUG:root:A total of 17 items/fluids were found for the reference list.
DEBUG:root:{'effectivity-module-2', 'ligma', 'speed-module-2', 'capybara', 'speed-module', 'productivity-module', 'doge', 'meme', 'effectivity-module-3', 'nuts', 'productivity-module-2', 'speed-module-3', 'balls', 'productivity-module-3', 'memepower', 'crack', 'effectivity-modu

test1
	With a vector of: {'nuts': 420, 'capybara': -3, 'memepower': -111}
	An added drain of: {'balls': -69}
	An effect matrix of: {'speed': ['nuts', 'capybara'], 'productivity': ['nuts'], 'consumption': ['memepower']}
	Allowed Modules: ['speed-module', 'speed-module-2', 'speed-module-3', 'effectivity-module', 'effectivity-module-2', 'effectivity-module-3', 'productivity-module', 'productivity-module-2', 'productivity-module-3']
	Base Inputs of: {'capybara': -9}
	A Cost of: {'meme': 2}
	Requiring: 
test2
	With a vector of: {'balls': 18, 'crack': -48, 'memepower': -232}
	An added drain of: {'ligma': -7}
	An effect matrix of: {'speed': ['balls', 'crack'], 'productivity': ['balls'], 'consumption': ['memepower']}
	Allowed Modules: ['speed-module', 'speed-module-2', 'speed-module-3', 'effectivity-module', 'effectivity-module-2', 'effectivity-module-3', 'productivity-module', 'productivity-module-2', 'productivity-module-3']
	Base Inputs of: {'crack': -2}
	A Cost of: {'doge': 3}
	Requiring: 

DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein sum

memepower: -3386.711358
crack: -535.9536


In [13]:
from utils import *
from generators import *
from constructs import *
compiled_construct.freeze(phi)

DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.
DEBUG:root:Running a sparse einstein summation.


In [12]:
import numpy as np
import pypoman

A = np.array([
    [-1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0],
    [0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
    [1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  1,  1,  1,  0,  0,  0,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0],
    [0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1],
    [1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0],
    [0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1,  0],
    [0,  0,  1,  0,  0,  1,  0,  0,  1,  0,  0,  1]])
b = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 2, 2, 1, 2, 3])

vertices = pypoman.compute_polytope_vertices(A, b)
vertices

[array([0., 0., 0., 1., 0., 0., 0., 0., 2., 0., 2., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 2., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 2., 1., 1., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 2., 0.]),
 array([1., 0., 0., 0., 0., 0., 0., 0., 2., 0., 2., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 2., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0.]),
 array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 2., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 2., 0.]),
 array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 2., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.]),
 array([0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 2., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 2., 0.]),
 array([0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 2., 0.]),
 array([1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 2., 0.]),
 array([0., 0., 2., 0., 0., 0., 1., 0., 0., 0., 2., 0.]),
 array([1., 0.

In [20]:
#many test for sparse tensor implementation
from sparsetensors import *

A = np.random.rand(*(100,25,15,5))*(np.random.rand(*(100,25,15,5))>.97)
B = np.random.rand(*(50,20,10,5))*( np.random.rand(*(50,20,10,5))>.95)
C = np.random.rand(*(150,45,25))
Asparse = SparseTensor(A.shape)
Bsparse = SparseTensor(B.shape)
Asparse.from_dense(A)
Bsparse.from_dense(B)
assert np.all(A==Asparse.to_dense())
assert np.all(B==Bsparse.to_dense())
edpnumpy = extra_dimensional_projection_numpy([A,B], [3])
edpmine = extra_dimensional_projection([Asparse,Bsparse], [3])
assert np.all(edpnumpy==edpmine.to_dense())
np.testing.assert_array_almost_equal(einstein_summation("ijkl,ijk", edpnumpy, C),
                                     einstein_summation("ijkl,ijk", edpmine, C))
Ar = SparseTensor(A.shape)
Ar.from_dense(A)
Ar.add_rank(0)
np.sum(Ar.to_dense())

2823.55709317594

0

In [13]:
for i in range(1, 2+3):
    print('ijkh'+''.join([chr(ord('l')+j) for j in range(i)])+',ijh,h,k,'+','.join([chr(ord('l')+j) for j in range(i)]))

ijkhl,ijh,h,k,l
ijkhlm,ijh,h,k,l,m
ijkhlmn,ijh,h,k,l,m,n
ijkhlmno,ijh,h,k,l,m,n,o
